[[bin]]
name = "Build"
path = "build.rs"

[build-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
tauri = { version = "2.4.0", features = ["devtools"] }
tauri-build = { version = "2.1.0", features = [] }

[dependencies]
unbug = { version = "0.4.0" }

[features]
Debug = []
custom-protocol = ["tauri/custom-protocol"]
default = []

[package]
name = "black-rainbow"
version = "0.0.1"

[target]

[target."cfg(windows)"]

[target."cfg(windows)".dependencies]
winapi = { version = "0.3.9", features = ["shellscalingapi"] }
