[package]
name = "tauri"
version = "0.0.1"

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
wry = "0.26.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.4", features = ["system-tray", "window-set-position"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
