[package]
name = "tauri"
version = "0.0.1"

[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
tauri = { version = "1.3.0", features = ["api-all", "devtools", "system-tray"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

[features]
custom-protocol = ["tauri/custom-protocol"]
