[package]
name = "tauri"
version = "0.0.1"

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
tauri = { version = "1.4.1", features = ["api-all", "devtools", "system-tray"] }
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"

[features]
custom-protocol = ["tauri/custom-protocol"]

[target."cfg(windows)".dependencies]
winapi = { version = "0.3.9", features = ["shellscalingapi"] }
