version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "cargo"
      directory: "/src-tauri"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only
